pipeline {
    agent any
    tools {
        maven "maven-nodo-principal"
    }
    stages {
        stage('Build') {
            steps {
                dir ("ejercicio-s-2-clase-17/maven-adderapp") {
                    sh 'mvn -DskipTests clean package'
                }
            }
        }
        stage('Test') {
            steps {
                dir ('ejercicio-s-2-clase-17/maven-adderapp') {
                    sh "mvn test"
                    }
                }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
    post {
        always {
            dir('ejercicio-s-2-clase-17/maven-adderapp') {
                junit 'target/surefire-reports/*.xml'
            }
        }
        success {
            dir ("ejercicio-s-2-clase-17/maven-adderapp") {
                archiveArtifacts artifacts: 'target/*.jar', fingerprint: true
            }
        }
    }
}